import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import Hero from "@/components/uncommon/Hero";
import Pricing from "@/components/uncommon/Pricing";
import Tools from "@/components/uncommon/Tools";
import Whyus from "@/components/uncommon/Whyus";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Script Scanner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Whyus />
      <Tools />
      <Footer />
    </>
  );
}
